[package]
authors = ["Stephen Sherratt <lecoqjacob@gmail.com>"]
edition = "2021"
name    = "vector"
version = "0.1.0"

[dependencies]
coord_2d   = "0.3"
rand       = "0.8"
rand_range = { path = "../rand-range" }
serde      = { version = "1.0", features = ["serde_derive"] }
