[package]
name = "vector"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
coord_2d = "0.3"
rand_range = { path = "../rand-range" }
rand = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
