version: '{build}'
clone_depth: 10
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      HOST: x86_64-unknown-linux-gnu
      TARGET: wasm32-unknown-unknown
      MODE: release

for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          TARGET: wasm32-unknown-unknown
    install:
      - sh: >-
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

          nvm use v16

          curl -sSf https://sh.rustup.rs | sh -s -- --quiet --default-host $HOST --default-toolchain stable --profile minimal -y

          export PATH="$HOME/.cargo/bin:$PATH"

          rustup target add $TARGET

          cargo install wasm-bindgen-cli --force --version 0.2.75 # this has to match the version in Cargo.lock

          cargo install wasm-pack

          rustc -V

          cargo -V

    build_script:
      - sh: >-
          pushd web

          npm install

          if [ "$MODE" == "release" ]; then
            BUILD_MODE=production
          else
            BUILD_MODE=development
          fi

          npm run build-production

          mkdir forgotten

          mv dist forgotten/$APPVEYOR_REPO_BRANCH

          zip -r forgotten.zip forgotten

          popd

          mv web/forgotten.zip .

    artifacts:
    - path: '*.zip'
      name: games.gridbugs.org

    deploy:
    - provider: Environment
      name: games.gridbugs.org