[package]
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"
name    = "rand_range"
version = "0.1.0"

[dependencies]
rand  = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
